
jobs:
- name: reconfigure
  serial: true
  plan:
  - get: src
    params: {depth: 1}
    trigger: true
  - set_pipeline: ((name))
    file: src/ci/pipeline.yml

- name: deploy-prod
  plan:
  - in_parallel:
    - get: src
      params: {depth: 1}
      trigger: true
      passed: [reconfigure]
  - task: generate-data
    file: src/ci/generate-data.yml
    tags: [iaas]
  - task: generate-html
    run:
      dir: src
      args:
        - npm run generate-html
  - put: cf-prod
    params:
      path: src
      manifest: src/manifest.yml
      show_app_log: true

---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

resources:
- name: src
  type: git
  source:
    commit_verification_keys: ((cloud-gov-pgp-keys))
    uri: ((dashboard-src-uri))
    branch: ((dashboard-src-branch))

- name: cf-prod
  type: cf
  icon: cloud-upload
  source:
    api: ((prod-cf-api-url))
    username: ((prod-cf-username))
    password: ((prod-cf-password))
    organization: ((dashboard-organization))
    space: ((dashboard-space))